config/routes.rb
Rails.application.routes.draw do
  devise_for :users



  resources :wikis
  resources :charges, only: [:new, :create]

  get "welcome/index"

  root 'welcome#index'
end

app/models/amount.rb
class Amount < ApplicationRecord
	private

	def self.default
		15_00
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
   
   after_create :send_favorite_emails
 
   private
 
   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         has_many :wikis, dependent: :destroy

  after_initialize :default_user_role

  enum role: [:member, :premium, :admin]

  
  def default_user_role
    self.role ||= :member
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:index, :about, :show]
    #before_action :prepare_meta_tags, if: -> { request.get? }
	#protect_from_forgery with: :exception
	  include Pundit
  protect_from_forgery
	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  # before_filter :authenticate_user!

  def new
    @stripe_btn_data = {

        #key: "#{ Rails.configuration.stripe[:publishable_key] }"
        :key => Rails.configuration.stripe[:publishable_key].to_s,
        :description => "Upgraded Membership - #{current_user.email}",
        :amount => 1500
    }
  end

  def create
    # Amount in cents
    @amount = 1500

    # Creates a Stripe Customer object, for associatingwith the charge
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :source => params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => "Upgraded Membership - #{current_user.email}",
      :currency => 'usd'
    )

    current_user.update_attribute(:role, 'premium')

    if current_user.save!
      flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
      redirect_to root_path(current_user) # or wherever
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def update

    if current_user.update!
      current_user.update_attribute(:role, 'standard')
      flash[:notice] = "Thanks for the opportunity, but you have been downgraded."
      redirect_to root_path(current_user) # or wherever
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
    @user = User.new
  end
   def create
    @user = User.new
    @user.name =                  params[:user][:name]
    @user.email =                 params[:user][:email]
    @user.password =              params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
     if @user.save
      flash[:notice] = "Welcome to Blocipedia, #{@user.name}!"
      redirect_to root_path
    else
      flash[:error] = "There was an error creating your account. Please try again."
      render :new
    end
  end
   def index
    @users = User.all
  end
   def show
  end
   def downgrade
    current_user.update_attribute(:role, 'standard')
     flash[:notice] = "#{current_user.email} account has been downgraded"
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController


  def index
    @wikis = Wiki.all
    # authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new

  end

  def create

    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to [@user, @wiki]
    else
      flash[:notice] = "There was an error. Please try again"
      render :new
    end
  end


  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end


  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    # @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:notice] = "There was an error. Please try again"
      render :edit
    end
  end



  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "The wiki:\"#{@wiki.id}\" has been deleted"
      redirect_to action: 'index'
    else
      flash[:alert] = "There was an error deleting the wiki"
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?

     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
   def devise_error_messages!
    return '' if resource.errors.empty?
     messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)
     html = <<-HTML
    <div class="alert alert-danger alert-block"> <button type="button" class="close" data-dismiss="alert">x</button>
        <h4>#{sentence}</h4>
        #{messages}
       </div>
       HTML
        html.html_safe
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<div class="space">
  <%= form_tag  charges_path do %>
    <h4>Upgrade my membership</h4>
    <p>$15 : upgrade your membership to have private wikis only other premium members can see.</p>
    <script class='stripe-button'
    Stripe.setPublishableKey('PUBLISHABLE_KEY');
    src="https://checkout.stripe.com/checkout.js"
    data-key="<%= @stripe_btn_data[:key] %>"
    data-amount="<%= @stripe_btn_data[:amount] %>"
    data-description="<%= @stripe_btn_data[:description] %>">
    </script>
  <% end %>
 </div>

app/views/comments/_comment.html.erb
<%= content_tag :div, class: 'media', id: "comment-#{comment.id}" do %>
   <div class="media">
     <div class="media-body">
       <small>
         <%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at) %> ago
         <% if user_is_authorized_for_comment?(comment) %>
           | <%= link_to "Delete", [@post, comment], method: :delete %>
         <% end %>
       </small>
       <p><%= comment.body %></p>
     </div>
   </div>
 
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
  crossorigin="anonymous">
</head>
<body>

  <container>
    <row>
      <div class="bg-success" style="height:130px;" >
        <br>
    <h1 style="margin-left:55px;">Blocipedia</h1>
    <p class="text-right" style="margin-right:50px;"><% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %> -
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %>
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
    <% end %></p>
    <h3 class="bg-warning text-right" >
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </h3>
  </div>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", welcome_index_path %></li>
            <li> <%= link_to "Wikis", wikis_path %></li>
            <li> <%= link_to "New Wiki", new_wiki_path %></li>
            <li> <%= link_to "Upgrade Membership", new_charge_path %></li>
        </ul>

    </div>
   </nav>

    </row>
  </container>




<%= yield %>

</body>
</html>

app/views/users/downgrade.html.erb
<h2>Your service has been downgraded. </h2> 

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron" style="margin-right:50px;margin-left:50px;">
   <h1 class="leftspace">Welcome</h1>
   <p style="margin-right:50px;margin-left:50px;">Wikis are a great way to collaborate on community-sourced content.
     Whether the wiki is for a hobby or work-related project, you will build
     an app that lets users create their own wikis and share them publicly or
     privately with other collaborators.</p>

 </div>

 <div class="row" style="margin-right:50px;margin-left:50px;">
   <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Bloccit will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Eliminates poverty</h2>
     <p>Bloccit will deliver money and education to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
   </div>
 </div>

app/views/wikis/_form.html.erb
<div class="space">
<%= form_for [user, wiki] do |f| %>
     <% if wiki.errors.any? %>
       <div class="alert alert-danger">
         <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
         <ul>
           <% wiki.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
        </ul>
      </div>
      <% end %>
      <div class="field form-group">
        <%= f.label :title, class: "control-label" %><br>
        <%= f.text_field :title, class: "form-control", placeholder: "Wiki Title" %>
      </div>
      <div class="field form-group">
        <%= f.label :body, class: "control-label" %><br>
        <%= f.text_area :body, cols: "30", rows: "10", class: "form-control", placeholder: "Wiki Body" %>
      </div>
      <% if current_user.role === "premium"  %>
        <div class="field form-group">
          <%= f.check_box(:private) %>
          <%= f.label(:private, "Make this wiki private") %>
        </div>
      <% end %>
      <div class="actions">
        <%= f.submit class:"btn btn-success btn-lg" %>
      </div>
<% end %>
</div>

app/views/wikis/edit.html.erb
<div class="space">
<h1>Edit a Wiki</h1>

  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for Wikis</p>
      <ul>
        <li>Make sure it talks about cool stuff.</li>
        <li>Refer to a Sci-fi show.</li>
        <li>Be respectful.</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= render partial: 'form', locals: { user: @user, wiki: @wiki } %>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="space">
  <h1> This is the wiki index </h1>
  <%= current_user.email %>
  <br>
  <p>The current time is: <%= Time.now %></p>
  <% time = Time.now %>
  <% if time < " 15:00:00 -0800" %>
  O Hai
  <%else%>
  Go get the la
  <%end%>
  <br>
  <%= user_signed_in? %>
  <br>
  <%= current_user.email %>
  <br>
  <%= current_user.role %>
  <br>

  <div class="col-md-8">
  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>
        <small>
          <%= wiki.body %>
        </small>
        <p>•  <% if wiki.private %>
            <small>private</small>
            <% else %>
            <small>public</small>
            <% end %> </p>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>

 <div class="row">

   <div class="col-md-4">
     <p>Guidelines:</p>
     <ul>
       <li>1</li>
       <li>2</li>
       <li>3</li>
     </ul>
   </div>

   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki content" %>
       </div>

       <% if current_user.role == 'premium' %>
         <div class="form-group">
           <%= f.label :private, class: 'checkbox' do %>
             <%= f.check_box :private %> Private wiki
           <% end %>
         </div>
       <% end %>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<div class="row ">
  <br>
  <ul class="space">
    <li class="btn btn-default" role="button"><%= link_to "Edit Wiki", edit_wiki_path %></li>
    <li class="btn btn-default" role="button"><%= link_to "Delete Wiki", wiki_path(@wiki), :method => :delete, data: { confirm: 'Are you sure you want to delete this wiki?' } %></li>
  </ul>
  <div class="col-md-8 space">
    <h1><%= @wiki.title %></h1>
    <p><%= @wiki.body %></p>

      <p>•<% if @wiki.private %>
          <small>private</small>
          <% else %>
          <small>public</small>
          <% end %>
    
    </p>
  </div>
</div>